// User Action Types
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

// Chat Action Types
export const CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";
export const CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT";
export const CHAT_ROOM_JOINED = "CHAT_ROOM_JOINED";
export const CHAT_ROOM_LEFT = "CHAT_ROOM_LEFT";

// News Action Types
export const NEWS_FETCH_SUCCESS = "NEWS_FETCH_SUCCESS";
export const NEWS_FETCH_FAIL = "NEWS_FETCH_FAIL";
export const NEWS_SAVE_SUCCESS = "NEWS_SAVE_SUCCESS";
export const NEWS_SAVE_FAIL = "NEWS_SAVE_FAIL";
export const NEWS_SAVED_ARTICLES_FETCH_SUCCESS =
  "NEWS_SAVED_ARTICLES_FETCH_SUCCESS";
export const NEWS_SAVED_ARTICLES_FETCH_FAIL = "NEWS_SAVED_ARTICLES_FETCH_FAIL";
